[versions]
agp = "8.5.2"
annotation = "1.9.1"
commonsLang3 = "3.17.0"
xposed = "82"

[libraries]
annotation = { module = "androidx.annotation:annotation-jvm", version.ref = "annotation" }
commons-lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang3" }
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }