[versions]
agp = "8.5.0"
dexkit = "2.0.2"
annotation = "1.8.0"
xposed = "82"

[libraries]
dexkit = { module = "org.luckypray:dexkit", version.ref = "dexkit" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }