[versions]
agp = "8.3.2"
xposed = "82"

[libraries]
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
library = { id = "com.android.library", version.ref = "agp" }