[versions]
agp = "8.3.2"
xposed = "82"
annotations = "28.0.0"

[libraries]
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }
annotations = { group = "com.android.support", name = "support-annotations", version.ref = "annotations" }

[plugins]
library = { id = "com.android.library", version.ref = "agp" }