[versions]
agp = "8.5.2"
annotation = "1.8.2"
xposed = "82"

[libraries]
annotation = { module = "androidx.annotation:annotation-jvm", version.ref = "annotation" }
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }