[versions]
agp = "8.5.0"
annotation = "1.8.0"
xposed = "82"

[libraries]
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }